---
title: "Project"
author: "Mark Kogo"
date: "2024-11-28"
output:
  pdf_document:
    latex_engine: xelatex
---
```{r}
install.packages("reshape2")
```

```{r, include=FALSE}
library(haven)
library(tidyverse)
library(dplyr)
library(stargazer)
library(margins)
library(broom)
library(ggplot2)
library(reshape2)
```
# Abstract 

# Introduction 

# Methods 
## Exploratory Data Analysis
```{r}
brazil_rev <- read.csv('~/Desktop/SOC 2202 PSET/data/BRAZIL_CITIES_REV2022.CSV')
```
```{r}
colnames(brazil_rev)
```
```{r}
# Data Visualizations
# Histogram of Life Expectancy Index
min(brazil_rev$IDHM_Longevidade)
brazil_rev <- brazil_rev %>% filter(IDHM_Longevidade > 0 & IDHM_Longevidade <= 1)

ggplot(brazil_rev, aes(x = IDHM_Longevidade))+
  geom_histogram(bins = 20, fill = "blue", alpha = 0.7, color = "black") +
  ggtitle("Distribution of Life Expectancy Index (IDHM_Longevidade)") +
  xlab("IDHM_Longevidade") +
  ylab("Frequency") +
  theme_minimal()
```

```{r}
# Scatterplot of Extractive Companies vs Life Expectancy
ggplot(brazil_rev, aes(x = IDHM_Longevidade, y =  COMP_B, color = RURAL_URBAN)) +
  geom_point(size = 3, alpha = 0.7) +
  scale_color_viridis_d() +
  ggtitle("Extractive Companies vs Life Expectancy") +
  ylab("Number of Extractive Companies (COMP_B)") +
  xlab("Life Expectancy Index (IDHM_Longevidade)") +
  theme_minimal()
```

```{r}
correlation_matrix <- brazil_rev %>% select(IDHM_Longevidade, COMP_B, GDP_CAPITA) %>% cor()
melted_corr <- melt(correlation_matrix)

ggplot(melted_corr, aes(x = Var1, y = Var2, fill = value)) +
  geom_tile(color = "white") +
  scale_fill_gradient2(low = "blue", high = "red", mid = "white", midpoint = 0) +
  geom_text(aes(label = round(value, 2)), color = "black") +
  ggtitle("Correlation Heatmap of Key Variables (Confounders)") +
  theme_minimal()
```

```{r}
ggplot(brazil_rev, aes(x = LONG, y = LAT, size = COMP_B, color = COMP_B)) +
  geom_point(alpha = 0.7) +
  scale_color_viridis_c() +
  ggtitle("Geospatial Distribution of Extractive Companies") +
  xlab("Longitude") +
  ylab("Latitude") +
  theme_minimal()
```
```{r}
ggplot(brazil_rev, aes(x = RURAL_URBAN, y = IDHM_Longevidade, fill = RURAL_URBAN)) +
  geom_boxplot(alpha = 0.7) +
  scale_fill_brewer(palette = "Set3") +
  ggtitle("Life Expectancy by Rural/Urban Typology") +
  xlab("Rural/Urban Typology") +
  ylab("Life Expectancy Index (IDHM_Longevidade)") +
  theme_minimal()
```

# Discussion 

# Results

